import "@/styles/globals.css";
import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import { Providers } from "./providers";
import {DashboardLayout} from "@/layouts";

const beVietNamPro = Be_Vietnam_Pro({
    weight: ["400", "500", "600", "700", "800"],
    style: "normal",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={beVietNamPro.className} suppressHydrationWarning>
                <Providers>
                    <DashboardLayout>{children}</DashboardLayout>
                </Providers>
            </body>
        </html>
    );
}
